# Generated by Django 4.2.13 on 2024-05-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(default='Título Padrão', max_length=100),
        ),
    ]
