# Generated by Django 4.2.13 on 2024-05-31 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_alter_post_titulo_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='titulo',
        ),
    ]
