# Generated by Django 4.2.13 on 2024-06-02 00:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0004_remove_post_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reacao_legal',
            field=models.ManyToManyField(blank='true', related_name='reacao_legal', to=settings.AUTH_USER_MODEL),
        ),
    ]
