# Generated by Django 4.2.13 on 2024-06-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_post_reacao_legal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reacao_legal',
        ),
    ]
